name: Create Jira Issue from release GH Release
run-name: Creating new tag in quay based on pushed tag in Github.
on:
  workflow_dispatch:
    inputs:
      component:
        description: 'ODH Component'
        required: true
      target_release:
        description: 'Target Downstream Release'
        required: true
      gh_org:
        default: 'opendatahub-io'
        description: 'Target Downstream Release'
        required: true
      repos:
        default: |
          [
            {
              "repo_name": "data-science-pipelines",
              "target_release": "v1.0.0",
              "previous_release": "v0.2.2"
            },
            {
              "repo_name": "data-science-pipelines-operator",
              "target_release": "v1.0.0",
              "previous_release": "v0.2.1"
            }
          ]
        description: 'Target Downstream Release'
        required: true
      labels:
        default: 'qe/verify'
        required: true
        description: ""
      jira_server:
        default: 'https://issues.redhat.com'
        required: true
        description: ""
      jira_project:
        required: true
        description: ""
      jira_labels:
        required: true
        description: ""
      jira_issue_type:
        default: "Feature Request"
        required: true
        description: ""
      jira_priority:
        default: 'Minor'
        required: true
        description: ""



jobs:
  gh-to-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          repository: HumairAK/gh-to-jira
          fetch-depth: '0'
      # Install dependencies
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Submit Jira
        run: |
          python src --component=${{ inputs.component }} \
            --target_release=${{ inputs.target_release }} \
            --org=${{ inputs.gh_org }} \
            --repos=${{ inputs.repos }} \
            --labels=${{ inputs.labels }} \
            --jira_server=${{ inputs.jira_server }} \
            --jira_project=${{ inputs.jira_project }} \
            --jira_labels=${{ inputs.jira_labels }} \
            --jira_issue_type=${{ inputs.jira_issue_type }} \
            --jira_priority=${{ inputs.jira_priority }}